### ISSUE TITLE
Improve sidebar

### ISSUE THREAD

**Issue by matzipan** [matzipan/eds-sample#3]
From @danrabbit: 
> For the sidebar, there's like 3 widgets that probably should be looked into:
> * http://valadoc.org/#!api=granite/Granite.Widgets.SourceList might be the easiest. It supports collapsible headers, badges, has the styling built in, etc
> * http://valadoc.org/#!api=gtk+-3.0/Gtk.StackSidebar is new and shiny, but I'm not sure if it deals with trees
> * Maximum effort, but would benefit all apps would be to maybe make a new SourceList widget that is a subclass of StackSidebar (edited)

**Comment by danrabbit** [comment]
Related to https://bugs.launchpad.net/pantheon-mail/+bug/1549520

We were looking at re-organizing the sidebar in the same way that the Nylas sidebar is structured. It seems like this method would scale really well and provide unified inboxes (which is a heavily requested features).

![screenshot from 2016-02-24 15-04-37](https://cloud.githubusercontent.com/assets/7277719/14227672/d2b318ba-f8b7-11e5-8996-98385a220588.png)

To kind of highlight what is special about this design is that they're doing a couple things:

- They group all common/special folders at the top. So things like Inbox and Trash are under the "All Acounts" header. Each of these folders are "unified" and can be expanded to access individual account folders. In other words, the parent item is the unified Inbox, child items are the inbox for Gmail and Work accounts. This is really interesting because of the nature of collapsing it makes it particularly scalable. Unlike the current organization where adding another account necessarily doubles the height of the sidebar items.

- They make labels/folders per account a header. This means that things that are unique about accounts are easily accessible, since they can't really be combined. Also unlike the current organization, it means labels/folders are exposed at the top level and not hidden under a collapsible item.

**Comment by matzipan** [comment]
Granite.Widgets.SourceList.ExpandableItem needs extra functionality so it can be selected without expanding.

As per discussion with @danrabbit: "Maybe if you click the item again while it's already selected it should expand. Just to make sure we have a large hit box in case you miss the disclosure triangle the first time"

**Comment by matzipan** [comment]
It turns out SourceList is nothing but a TreeView in nice clothing. I will be trying to build a new nested layout structure based on Gtk.ListBox.

**Comment by matzipan** [comment]
Right now the structure is
```
ListBox
   Expandable ListBoxRow
   Child ListBoxRow
   Child ListBoxRow
```

After I finish this implementation, I will experiment with the following
```
ListBox
    Expandable ListBoxRow
        ListBox
              Header ListBoxRow
              Child ListBoxRow
              Child ListBoxRow
```

The latter will give nice nestedness for styling and I guess would be easier to wrap in a Revealer for animation, etc.

**Comment by matzipan** [comment]
For reference, this is the OS X Mail sidebar
![screen shot 2016-04-10 at 13 37 38](https://cloud.githubusercontent.com/assets/317239/14410209/a57096dc-ff21-11e5-96c5-26be62e0fee0.png)

**Comment by matzipan** [comment]
Mail on OS X with multiple accounts
![13833459_1405455462815091_998827275_o](https://cloud.githubusercontent.com/assets/317239/17253650/f0078d22-55b1-11e6-8fad-c97ae4bbebc8.png)
